Useful plugins and how to install them
corso-android-ivan-morgillo/docs pull request #4
Opened 2021-01-15 11:51 UTC by alaudiero

2021-01-15 11:56 UTC, alaudiero commented
Ho sbagliato a scrivere premuti

2021-01-15 14:57 UTC, hamen approved these changes

2021-01-15 14:57 UTC, hamen commented on README.md
> +* Aprire l'ide android studio.
Correggi IDE e A... S..., please

2021-01-15 14:59 UTC, hamen requested changes
Mergio appena correggi 👍

2021-01-17 10:41 UTC, alaudiero reviewed
Fatto

2021-01-17 11:28 UTC, merged